---

- hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - include_vars: config.yml
  - include: ec2.yml


- hosts: public
  gather_facts: no
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - include_vars: config.yml
  - include: node.yml 
  - include: cluster.yml 


- hosts: master
  gather_facts: no
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - include_vars: config.yml
  - include: jupyter.yml
  - include: examples.yml
  - include: master.yml


- hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - include: local.yml

